// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADBYgb9OSleC_PTd0UPuy1Er8CqvucXcw',
    appId: '1:411765918979:web:98b08e864a6395a24f6d36',
    messagingSenderId: '411765918979',
    projectId: 'project-568166903627460027',
    authDomain: 'project-568166903627460027.firebaseapp.com',
    databaseURL: 'https://project-568166903627460027-default-rtdb.firebaseio.com',
    storageBucket: 'project-568166903627460027.appspot.com',
    measurementId: 'G-1FVQWQH683',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmdhOJUkE31Z76w7HyvDvoOrByyAwHqTU',
    appId: '1:411765918979:android:c01c894d335cf9294f6d36',
    messagingSenderId: '411765918979',
    projectId: 'project-568166903627460027',
    databaseURL: 'https://project-568166903627460027-default-rtdb.firebaseio.com',
    storageBucket: 'project-568166903627460027.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2lV7aucruQRXepCYtMjnRB-qAE3hdCMQ',
    appId: '1:411765918979:ios:f533349d6087ea3e4f6d36',
    messagingSenderId: '411765918979',
    projectId: 'project-568166903627460027',
    databaseURL: 'https://project-568166903627460027-default-rtdb.firebaseio.com',
    storageBucket: 'project-568166903627460027.appspot.com',
    iosClientId: '411765918979-ohkllb345ptito2410q11ii5mc50nibe.apps.googleusercontent.com',
    iosBundleId: 'com.call0953.call0953Manager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2lV7aucruQRXepCYtMjnRB-qAE3hdCMQ',
    appId: '1:411765918979:ios:64d2c0d0362b90394f6d36',
    messagingSenderId: '411765918979',
    projectId: 'project-568166903627460027',
    databaseURL: 'https://project-568166903627460027-default-rtdb.firebaseio.com',
    storageBucket: 'project-568166903627460027.appspot.com',
    iosClientId: '411765918979-d18p3jggveck304398ic21ohm6dad4q8.apps.googleusercontent.com',
    iosBundleId: 'com.example.call0953Manager.RunnerTests',
  );
}
